### PR TITLE
Add Xiaomi Zero Fog Humidifier (shuii.humidifier.jsq001) support (#52)

### PR DESCRIPTION
**Pull request by iromeo**
Xiaomi Zero Fog Humidifier (shuii.humidifier.jsq001) support (#52). 

This pull request depends on my changes to `python-miio` library (see  https://github.com/rytilahti/python-miio/issues/642) which will be available in the next library update

### CODE REVIEW

**Comment by iromeo** [comment]
My changes already available in `python-miio` 0.5.0.1, so this pull request is ready for review

**Comment by iromeo** [comment]
@syssi Hi, I'd like to get some feedback on PR and what steps are required to merge it and included into next release. Could you take a look on it?

**Comment by iromeo** [comment]
Slightly updated version send as PR to HA directly (https://github.com/home-assistant/core/pull/33736).

**Comment by syssi** [comment]
Thanks for your PR! Sorry for the late feedback. I wasn't aware of your PR right now. I will provide a code review asap!

**Comment by iromeo** [comment]
@syssi I've sent a rather refactored version of this PR to https://github.com/home-assistant/core/pull/33736  but they want somebody to re-implement everything and do not use 'fan' platform for humidifiers any more.

**Comment by syssi** [comment]
I would like to merge your feature here for the meantime. Could you fix the conflict?

**Comment by iromeo** [comment]
Please wait a bit with merging this, I'd like to compare this version with my fork and HA pull request, probably this version is a bit out of date. I'll have some time to do it at the weekend.

**Comment by syssi** [comment]
Alright! I marked your pull request as draft now. Just click "ready for review" if you're done.

**Comment by syssi** [comment]
Ping! :-)

**Comment by iromeo** [comment]
Hi, I was on vacation recently, I'll take a look at this at the end of the month.

**Pull request merged**
