### PR TITLE
Add dmaker.airfresh.a1 support

### PR DESCRIPTION
**Pull request by syssi**
TODO: 

- set_filter_rate 100 to reset the filter lifetime.
- What about: switch_power, switch_mode, get_sensor, get_speed?

Supported methods:
- [x] `set_power [power]` on/off
- [x]  `set_mode [mode]` sleep/auto/favourite
- [x]  `set_favourite_speed` 0...150
- [ ]  `get_sensor [sensor]` pm25/co2 (at the mihome app pm25 values above 999 are capped to 999)
- [x]  `set_ptc_on [on/off]`
- [ ] `get_timer []`
- [ ] `get_ptc_timer []`
- [ ] `set_ptc_timer [ptcTime]`
- [ ] `set_timer [time]`
- [ ] `get_light_timer []`
- [ ] `set_light_timer [lightTime]`
- [ ] `delete_timer [time]`
- [x] `set_display [light]` on/off(?)
- [x] `set_sound [sound]` on/off
- [x] `set_child_lock [lock]` on/off
- [x] `set_filter_reset [filter]`

Supported properties:

- [x] `pm25`
- [x] `co2`
- [x] `temperature_outside`
- [x] `favourite_speed`
- [x] `filter_rate`
- [x] `filter_day`
- [x] `control_speed`
- [x] `power`
- [x] `mode`
- [x] `ptc_on`
- [x] `ptc_status`
- [x] `child_lock`
- [x] `sound`
- [x] `display`
 
Getter and setter of `ptc_level` and `screen_direction` is not supported!

Example `get_prop` response:

```
$ miiocli device --ip IP --token TOKEN raw_command get_prop '["power", "pm25", "co2", "temperature_outside", "favourite_speed", "filter_rate", "filter_day", "control_speed", "ptc_on", "ptc_status", "child_lock", "sound", "display", "mode"]'
Running command raw_command
[True, 2, 554, 12, 150, 45, 81, 60, False, False, False, False, False, 'auto']
```

### CODE REVIEW

**Comment by skvalex** [comment]
Filters on this device have RFID-tag, so the device knows itself when the filter is being changed. So method `set_filter_reset` does not work at all.
Range is 0-150 for `set_favourite_speed`.
Also, this device accepts `true`/`false` instead of `on`/`off`, just like `dmaker.airfresh.t2017` model does: https://github.com/rytilahti/python-miio/pull/854

**Comment by syssi** [comment]
@skvalex Are you aware of this command (rate vs reset) to reset the filter lifetime: https://github.com/rytilahti/python-miio/issues/662#issuecomment-653946395

**Comment by skvalex** [comment]
@syssi I don't have access to this device now, but I have played with it in January and have added support for openhab then.
So, according to the [config](https://github.com/skvalex/openhab2-addons/blob/5ff83098bbd3792623c12beb87fb25126b1c236d/bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.airfresh.a1.json) I created, `filter_rate` is for filter life remaining in percents and `filter_day ` is for days remaining.
As I [said](https://github.com/syssi/xiaomi_airpurifier/pull/97#issuecomment-727118735) before, `set_filter_reset` doesn't work there at all, so it can be removed completely. At the time of writing [config](https://github.com/skvalex/openhab2-addons/blob/5ff83098bbd3792623c12beb87fb25126b1c236d/bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.airfresh.a1.json) for openhab I couldn't test it, because the filter was 100%, that's why `set_filter_reset` exists in my config.

**Comment by alexmorbo** [comment]
Any news? A have dmaker.airfresh.a1
From https://github.com/NikolayBorisov/xiaomi_airfresh a got works:
- Turn on / off
- fan.airfresh_set_favourite_speed - from 1 to 200
- switch.xiaomi_a1_display - on / off
- switch.xiaomi_a1_sound - on / off
- switch.xiaomi_a1_ptc - on / off (heat)
- sensor.xiaomi_a1_co2
- sensor.xiaomi_a1_pm25

Not works:
- fan.set_speed - [miio.protocol] Unable to decrypt, returning raw bytes: b''

**Comment by rdhlb** [comment]
Hey guys

Any news on this one? Is there anything I can do to help this going (e.g. provide logs, debug, test, etc)?

I've got this device and would really like to integrate it into HA.

**Comment by rdhlb** [comment]
Hey @syssi 

Sorry for being annoying here. Just trying to figure out if I can do anything to help finish this up and merge.

**Comment by syssi** [comment]
The next step is to prepare a python-miio release. As soon the new version is released this PR can be merged.

**Pull request merged**
