### PR TITLE
Add retries option for MIOT air purifier

### PR DESCRIPTION
**Pull request by bieniu**
This PR adds `retries` option for MIOT air purifiers and the logic to repeat device status update in case of error. This is the same solution as for `XiaomiFan` class.

Example of configuration:
```
fan:
    - platform: xiaomi_miio_airpurifier
      name: Air Purifier Living Room
      model: zhimi.airpurifier.mb3
      host: 192.168.178.26
      token: !secret airpurifier_token
      retries: 2
```

This PR is a workoround for https://github.com/syssi/xiaomi_airpurifier/issues/82

### CODE REVIEW

**Review by syssi — APPROVED** [review]
Good job! Thanks!

**Comment by mouth4war** [comment]
The official integration needs this! This PR fixed my 3Hs spotty availability.

**Comment by ssergiio** [comment]
> 

Hey could you point me out on how to use this integration vs the official one? I installed it and added the OP config with my IP and token to my configuration.yaml but the device and entities aren't showing. What I'm I missing out? Searched but couldn't find anything.

Thanks!

**Comment by mouth4war** [comment]
You won't get devices with this custom component. Check your logs to see what the error is. Also, open an issue instead of replying here

**Pull request merged**
