### PR TITLE
Removed Wet Protection preset mode for deerma.humidifier.mjjsq

### PR DESCRIPTION
**Pull request by Anonym-tsk**
deerma.humidifier.mjjsq and deerma.humidifier.jsq don't support wet protection mode.
Remove it from preset_mode

### CODE REVIEW

**Comment by Anonym-tsk** [comment]
So, i'm not sure. Maybe it's better to remove wet protection from deerma.humidifier.jsq1 too?
I have deerma.humidifier.jsq1 and it doesn't support wet protection and this preset mode throws error.

**Comment by syssi** [comment]
I will try to lookup the different features of the different devices this weeking.

**Comment by Anonym-tsk** [comment]
Any updates?

**Comment by syssi** [comment]
It's more complicated as I had expected. I'm on it!

**Comment by syssi** [comment]
I've checked the android plugin of the `jsq1` and I want to keep the wet & protect feature for now.

**Pull request merged**
