### PR TITLE
fixed null value error in template

### PR DESCRIPTION
**Pull request by iStitch07**
fixed null value error in template while device is off

### CODE REVIEW

**Comment by syssi** [comment]
Is `Auto` a good choice if no preset mode is available?

**Comment by iStitch07** [comment]
I think yes, because after turning on device really mode will be set automatically.

**Comment by iStitch07** [comment]
It's worked some like this

https://youtu.be/CsAac0_rdKw

**Comment by syssi** [comment]
Cool! Let's merge the fix!

**Pull request merged**
