### PR TITLE
deerma.humidifier.jsq5 support

### PR DESCRIPTION
**Pull request by dpozimski**

### CODE REVIEW

**Comment by syssi** [comment]
Good job!

**Review by syssi — APPROVED** [review]

**Comment by re-id** [comment]
HA accepts saving configuration with deerma.humidifier.jsq5
But there is still an error in integration
P.S. Sorry for my English

Logger: custom_components.xiaomi_miio_airpurifier.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:1687
Integration: xiaomi_miio_airpurifier (documentation, issues)
First occurred: 11:12:06 (16 occurrences)
Last logged: 11:19:40
Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}

fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air
    host: 192.168.38.40
    token: 879faba276a3f749630a8299a6ef5c48
    model: deerma.humidifier.jsq5

**Comment by shurakenas** [comment]
как добавить room?

**Comment by kvladimirovich10** [comment]
@dpozimski hello!

Can you please check your changes? Looks like there's still some problem with this specific model (deerma.humidifier.jsq5)
https://github.com/syssi/xiaomi_airpurifier/issues/229

**Comment by dpozimski** [comment]
the protocol for this concrete model is different than for the previous revisions of xiaomi purifiers,
unfortunately there is no workaround to make it work,
the support can be provided using alternative lib like here:
https://github.com/al-one/hass-xiaomi-miot

**Comment by kvladimirovich10** [comment]
> the protocol for this concrete model is different than for the previous revisions of xiaomi purifiers,
> unfortunately there is no workaround to make it work,
> the support can be provided using alternative lib like here:
> https://github.com/al-one/hass-xiaomi-miot

Thanks for your answer. Yesterday I figured it out as well and It worked. 
Hope to see a working integration through Xiaomi Miio soon.

**Pull request merged**
